import Link from "next/link";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { PageHeader } from "@/components/PageHeader";
import { createMetadata } from "@/lib/metadata";
import { casebankArchive, formatArchiveCount } from "@/lib/casebank-archive";
import { casebankCards } from "@/lib/casebank";
export const metadata = createMetadata({ title: "Editorial Policy and Case Provenance | Hanjin Jang, MD", description: "Standards for authorship, evidence, clinical records, privacy, missing data, review dates, and corrections.", path: "/editorial-policy" });
const sections = [
  { title: "Purpose and audience", body: "This is Hanjin Jang, MD's academic profile and educational resource. Clinical topics, operative concepts, publications, and Casebank records serve professional education. Plain-English patient guides are labeled separately. Individual treatment decisions require a clinical assessment." },
  { title: "Authorship and clinical review", body: "The profile identifies Hanjin Jang, MD and links to the official institutional biography. Existing educational material is attributed to its source collection. Authorship, website maintenance, and independent clinical review are separate roles. A reviewer and review date are stated only when a specific review record is available. An omitted review date does not imply a recent review." },
  { title: "Sources and citations", body: "Prefer original journal records, clinical guidelines, and institutional sources. Publications show the source's author spelling, citation, DOI, year, and historical affiliation. External clinical evidence is labeled separately from Dr. Jang's publications. The reading list is curated and does not claim to be exhaustive or a systematic review. Conference details require an original program before use as formal citations." },
  { title: "Casebank provenance", body: `Casebank presents ${casebankCards.length} selected public teaching entries: seven previously public clinical summaries, one existing operative-video example and one case from a coauthored journal article. Each entry identifies its source and information gaps. A separate aggregate summary describes ${formatArchiveCount(casebankArchive.clinicalRecords)} private clinical archive records, ${casebankArchive.historicalVideoCases} historical video case records and a ${casebankArchive.videoCatalogueCases}-case video catalogue. Collections may overlap and are not added together. These counts are not a consecutive patient registry, a lifetime count of unique operations, verified UBE volume or an outcomes dataset.` },
  { title: "Observations and missing data", body: "Keep the distinction between clinical presentation, the recorded treatment rationale, operative details, imaging, and patient outcomes. Unreported data remain marked as not reported. They are never replaced by assumed normal findings or zero complications. Without defined observation periods and denominators, the collection cannot support success-rate or complication-rate calculations." },
  { title: "Clinical images, consent, and privacy", body: "New clinical material requires confirmation of the applicable publication authorization and a documented privacy review before release. Remove identifiers from images, filenames, captions, embedded metadata, and video or audio tracks. Use case-matched clinical images; do not fabricate diagnostic images or substitute unrelated images. This update reuses existing public assets and adds no private patient files. It does not retrospectively certify consent records unavailable in the published source." },
  { title: "Dates and automated assistance", body: "Publication dates belong to the original source. Page updates record substantive website changes; clinical review dates record documented medical reviews. Automated assistance was used in the September 2026 reorganization for structure, citation formatting, aggregate recounts, navigation and technical checks. AI suggestions were compared with the public sources before editorial changes were made. AI output is not a clinical source, independent medical review, institutional endorsement or verification of an underlying patient chart." },
  { title: "Institutional interests and disclosures", body: "The site presents the professional work of Hanjin Jang, MD, Founder and Chief Director of New Standard Hospital, and links to that institution. Financial and competing-interest statements for a journal article should be read in the original publication. Missing information is not evidence of an absence of conflicts. The cases are not ranked by commercial treatment or device preference." },
  { title: "Corrections", body: "Send the page URL, the passage at issue and a supporting public source through the institutional contact route. Do not include patient identifiers in general correspondence. A request is not treated as a confirmed correction until its source and scope are checked. Factual corrections record the affected page, change and date; medical changes require an attributable clinical review. No response-time guarantee or completed review is implied." }
];
export default function EditorialPolicyPage() {
  return <><Breadcrumbs items={[{ name: "Home", href: "/" }, { name: "Editorial Policy", href: "/editorial-policy" }]} />
    <PageHeader compact eyebrow="Trust · Sources · Accountability" title="Editorial policy" description="How this academic resource attributes work, presents evidence, protects clinical material, and records information gaps."><p className="mt-4 text-sm text-slate-600">Policy updated September 12, 2026</p></PageHeader>
    <section className="mx-auto max-w-4xl px-5 py-12">
      <section id="review-status" className="mb-10 scroll-mt-24 border border-academic-line bg-academic-panel p-6">
        <h2 className="font-serif text-2xl text-academic-navy">Current review status</h2>
        <dl className="mt-5 grid gap-5 text-sm leading-7">
          <div><dt className="font-semibold text-academic-navy">Website edition · September 12, 2026</dt><dd className="mt-1 text-slate-600">Public source links, collection definitions, aggregate counts, author order and website behavior have been checked within their stated scope.</dd></div>
          <div><dt className="font-semibold text-academic-navy">Independent case-level medical review</dt><dd className="mt-1 text-slate-600">A named independent reviewer and review date are not documented for this website edition. The underlying patient charts have not been re-audited for this update. The journal-based entry retains the source article&apos;s publication and review context; that does not make this website a peer-reviewed journal.</dd></div>
          <div><dt className="font-semibold text-academic-navy">Clinical interpretation</dt><dd className="mt-1 text-slate-600">Teaching entries preserve missing findings and follow-up as unreported. The level distribution covers the {casebankCards.length} open entries only. Archive counts do not verify procedure type, treatment success or a complication rate.</dd></div>
        </dl>
      </section>
      <div className="grid gap-9">{sections.map((section) => <section key={section.title} className="border-l-2 border-academic-line pl-5"><h2 className="font-serif text-2xl text-academic-navy">{section.title}</h2><p className="mt-3 text-sm leading-8 text-slate-700">{section.body}</p></section>)}</div>
      <section id="video-publication" className="mt-9 border-l-2 border-academic-line pl-5">
        <h2 className="font-serif text-2xl text-academic-navy">Video inventory and publication</h2>
        <p className="mt-3 text-sm leading-8 text-slate-700">The <Link href="/casebank#drive-inventory" className="underline">Drive inventory</Link> records files in the identified source collections, including empty entries and possible copies. A file listing, filename match or upload to private storage does not establish a clinical case or authorize public release. Source permission, privacy review, a reliable connection to the clinical record and medical context are checked before adding new footage.</p>
        <p className="mt-3 text-sm leading-8 text-slate-700">The <Link href="/videos" className="underline">open video collection</Link> reuses the existing Case 08 educational sequence. Its new watch page provides chapter navigation, a transcription of the on-screen captions and a Korean translation. These are website and accessibility changes. No new spoken commentary by Dr. Jang, patient outcome or independent medical review is claimed. Video duration is kept separate from operative time, and alternate edits remain the same teaching entry.</p>
        <p className="mt-3 text-sm leading-8 text-slate-700">September 12, 2026 video update: added the dedicated watch page and video index, checked the existing file duration and caption transitions, linked the case and source article, published aggregate inventory definitions, and added video search metadata and a video sitemap.</p>
      </section>
      <section id="revision-history" className="mt-10 border-t border-academic-line pt-8"><h2 className="font-serif text-2xl text-academic-navy">Substantive revision history</h2><ol className="mt-5 grid gap-5 text-sm leading-7 text-slate-600"><li><time dateTime="2026-09-11" className="font-semibold text-academic-navy">September 11, 2026</time> — Introduced individual Casebank pages, level counts, a selected bibliography, an evidence library and source limitations.</li><li><time dateTime="2026-09-12" className="font-semibold text-academic-navy">September 12, 2026 · Archive edition</time> — Added the aggregate archive counts and annual counting method to Casebank, Home and About. No private patient rows or new clinical outcomes were published.</li><li><time dateTime="2026-09-12" className="font-semibold text-academic-navy">September 12, 2026 · Transparency update</time> — Clarified the open collection in the Casebank introduction and search description, limited level statistics to open entries, added a downloadable aggregate summary, connected author identity sources and stated the published author order. Updated this policy to reflect the archive and the current medical-review status.</li></ol></section>
      <Link href="/contact#corrections" className="mt-8 inline-block bg-academic-navy px-5 py-3 font-semibold text-white">Academic inquiries and corrections →</Link>
    </section>
  </>;
}
